sudo: false
language: haskell

cabal: "2.4"
ghc:
  - "8.4.4"
  - "8.10.1"

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.cabal

before_install:
# Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH

script:
  - cabal update
  - mkdir -p packaging/usr/bin
  - cabal test
  - cabal install
  - cp ~/.cabal/bin/die packaging/usr/bin/
  - chmod 755 packaging packaging/usr packaging/usr/bin packaging/usr/bin/die
  - chmod 755 packaging/DEBIAN packaging/DEBIAN/p* packaging/DEBIAN/config
  - chmod 644 packaging/DEBIAN/control
  - dpkg-deb -b packaging die.x86_64.deb
