sudo: false
language: haskell

ghc:
  - "7.10.3"
  - "8.4.4"
  - "8.10.1"

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.cabal

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH

script:
    - mkdir -p packaging/usr/bin
    - cabal update
    - cabal install cabal-install
    - cabal --installdir=packaging/usr/bin --install-method=copy install
    - chmod 755 packaging packaging/usr packaging/usr/bin packaging/usr/bin/die
    - chmod 755 packaging/DEBIAN packaging/DEBIAN/p* packaging/DEBIAN/config
    - chmod 644 packaging/DEBIAN/control
    - dpkg-deb -b packaging die.x86_64.deb
