# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: die
version: '1.0.2'
github: "fuszenecker/die"
license: MIT
author: "Róbert Fuszenecker"
maintainer: "Róbert Fuszenecker"
# synopsis: A new Haskeleton package.
# description: die is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - with-utf8
  - time
  source-dirs: library

executables:
  die:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - die
    ghc-options:
    #- -rtsopts
    - -threaded
    #- -with-rtsopts=-N
    - -O

benchmarks:
  die-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - die
    - criterion
    ghc-options:
    #- -rtsopts
    - -threaded
    #- -with-rtsopts=-N
    - -O

tests:
  die-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - die
    - tasty
    - tasty-hspec
    ghc-options:
    #- -rtsopts
    - -threaded
    #- -with-rtsopts=-N
    - -O
