name:                HaskellDemo
version:             2.0.0.0
github:              "githubuser/fuszenecker/HaskellDemo"
license:             MIT
author:              "Fuszenecker Róbert"
maintainer:          "robert.fuszenecker@outlook.com"
copyright:           "2019, Fuszenecker Róbert"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/x#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - parallel
  - monad-par

executables:
  HaskellDemo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellDemo
    - parallel
    - monad-par

tests:
  HaskellDemo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellDemo
